# Generated by Django 4.0.5 on 2022-06-22 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcategory',
            name='run_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TestCategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
