# Generated by Django 4.0.5 on 2022-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0002_alter_testcategory_run_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
