# Generated by Django 4.0.5 on 2022-06-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0003_testcategory_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name_plural': 'Test Categories'},
        ),
    ]
