# Generated by Django 4.0.5 on 2022-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0004_alter_testcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='forest_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
