# Generated by Django 4.0.5 on 2022-06-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0005_testcategory_forest_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='activate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='active_users_who_cannot_change_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='active_users_whose_password_never_expires',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='active_users_whose_password_not_required',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='aging_enabled',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='all_users_who_cannot_change_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='all_users_whose_password_never_expires',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='all_users_with_bad_primary_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='all_users_with_password_not_required',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='all_users_with_sid_history',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='applies_to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='bios',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='check_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='complexity_enabled',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='computer_extension_datas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='computer_sys_vol_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='dhcp_enabled',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='domain_mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='enabled',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='enabled3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='enforced',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='free_spaces',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='global_groups',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='gpo_inheritance_blocked',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='gpo_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='groups',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='groups_with_sid_history',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='infrastructure_master',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='install_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='is_ds_intergrated',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='is_shutdown',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='links_to_enabled',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='lockout_duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='lockout_observation_window',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='lockout_threshold',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='max_password_age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='maximum_kilo_bytes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='member_of',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='members1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='members2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='min_password_age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='min_password_length',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='modification_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='name1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='operating_system',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='operating_systems',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='os_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='password_history_count',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='password_last_set',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='password_never_expires',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='password_not_required',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='pdc_emulator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='present',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='protected_from_accidental_deletion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='replication_scope',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='reversible_encryption_enabled',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='rid_master',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='scavenging_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='schema_master',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='schema_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='servers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='sid_filtering_forest_aware',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='sid_filtering_quarantined',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='tcpi_net_bios_options',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='test_results',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='tgt_delegation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='total_physical_memory',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='transport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='universal_groups',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='user_authentication_required',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='user_extension_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='user_sys_vol_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='users',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
