# Generated by Django 4.0.5 on 2022-06-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0006_testcategory_activate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='deletion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
