# Generated by Django 4.0.5 on 2022-06-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0007_testcategory_deletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name_plural': 'Test-Categories'},
        ),
    ]
