# Generated by Django 4.0.5 on 2022-06-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testzone', '0008_alter_testcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name_plural': 'TestCategories'},
        ),
    ]
