from django.forms import ModelForm

from .models import TestCategory


class CategoryForm(ModelForm):
    class Meta:
        model = TestCategory
        fields = ['title',
                  'description',
                  'score',
                  'run_by',
                  'run_in',
                  'forest_mode',
                  'schema_master',
                  'operating_system',
                  'enabled',
                  'schema_version',
                  'present',
                  'servers',
                  'sid_filtering_forest_aware',
                  'sid_filtering_quarantined',
                  'tgt_delegation',
                  'domain_mode',
                  'infrastructure_master',
                  'pdc_emulator',
                  'rid_master',
                  'source',
                  'password_history_count',
                  'max_password_age',
                  'min_password_age',
                  'reversible_encryption_enabled',
                  'complexity_enabled',
                  'min_password_length',
                  'lockout_duration',
                  'lockout_observation_window',
                  'lockout_threshold',
                  'applies_to',
                  'name',
                  'deletion',
                  'gpo_inheritance_blocked',
                  'groups_with_sid_history',
                  'members1',
                  'members2',
                  'users',
                  'groups',
                  'global_groups',
                  'universal_groups',
                  'modification_time',
                  'enabled',
                  'enforced',
                  'check_type',
                  'all_users_whose_password_never_expires',
                  'all_users_with_password_not_required',
                  'all_users_who_cannot_change_password',
                  'all_users_with_sid_history',
                  'all_users_with_bad_primary_group',
                  'active_users_whose_password_never_expires',
                  'active_users_whose_password_not_required',
                  'active_users_who_cannot_change_password',
                  'member_of',
                  'password_last_set',
                  'password_never_expires',
                  'password_not_required',
                  'display_name',
                  'links_to_enabled',
                  'gpo_status',
                  'computer_extension_datas',
                  'user_extension_data',
                  'computer_sys_vol_version',
                  'user_sys_vol_version',
                  'os_version',
                  'activate',
                  'operating_systems',
                  'maximum_kilo_bytes',
                  'total_physical_memory',
                  'bios',
                  'free_spaces',
                  'dhcp_enabled',
                  'tcpi_net_bios_options',
                  'enabled3',
                  'transport',
                  'name1',
                  'install_state',
                  'user_authentication_required',
                  'scavenging_state',
                  'ip_address',
                  'replication_scope',
                  'is_ds_intergrated',
                  'is_shutdown',
                  'aging_enabled',
                  'test_results']

    def __int__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'input'
        self.fields['title'].widget.attrs['v-model'] = 'title'
        self.fields['description'].widget.attrs['class'] = 'description'
